# These are supported funding model platforms
funding:
  github: andev0x
  gitee: andev0x
  patreon: andev0x
  ko-fi: andev0x
  custom:
    url: https://github.com/sponsors/andev0x/
    description: "Support my work on this project"
    image: https://raw.githubusercontent.com/aha999/DonateButtons/master/Paypal.png
